description: Express interest in possible new multiformats project
title: "📚 [NEW PROJECT] - <title>"
labels: [
  "Ideas"
]
body:
  - type: input
    id: name
    attributes:
      label: "Name"
      description: Name this multi- in a word, if you can
      placeholder: Multi-thingy for now
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: "Have read contributing"
      description: I have read the [contributing](./contributing.md) document
      options:
      - label: I read it!
    validations:
      required: true
  - type: textarea
    id: problem_statement
    attributes:
      label: "Description of problem solved"
      description: Please describe the problem solved by a mini-registry within multiformats
      placeholder: Feel free to provide links for context and use-case descriptions, and how this problem is not solved by existing multi-formats entries or mini-registries
    validations:
      required: true
  - type: textarea
    id: prior_art
    attributes:
      label: "Description of relevant prior art and status quo"
      description: Please describe relevant prior art and how this is use-case functions today
      placeholder: Links welcome
    validations:
      required: true
  - type: textarea
    id: solution_and_rationale
    attributes:
      label: "Proposed solution and rationale"
      description: Please describe at a high level what a new multi- registry or new tooling for existing registries would enable and discuss tradeoffs and rationale (for new sub-registry in particular)
      placeholder: Detail welcome
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Have checked table"
      description: I have reviewed the [multiformats mega-table](https://github.com/multiformats/multicodec/blob/master/table.csv) to assess viable sub-namespace for a registry if applicable
      options:
      - label: I read it!
  - type: textarea
    id: registry_design
    attributes:
      label: "Proposed sub-namespace"
      description: Please describe the range of entries your project would need and any considerations about the greater multiformats namespace
      placeholder: Registration space need not be contiguous and one entry in the macro-registry can be annotated differently in multiple sub-registries
    validations:
      required: true